//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppraisalStaffDetails
    {
        public int AppraisalStaffDetails_Id { get; set; }
        public Nullable<int> AppraisalStaff_Id { get; set; }
        public Nullable<int> PerformanceCriterion_Id { get; set; }
        public Nullable<decimal> ro_perf_rating_yearMid { get; set; }
        public Nullable<decimal> ro_perf_rating_yearEnd { get; set; }
        public string staff_comments { get; set; }
        public string ro_comments { get; set; }
        public Nullable<bool> disabled { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
    }
}
