//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppraisalStaff
    {
        public int AppraisalStaff_Id { get; set; }
        public Nullable<int> Appraisal_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> AppraisalStatus_Id { get; set; }
        public Nullable<int> Form_Id { get; set; }
        public Nullable<decimal> Sec1_total_points_score { get; set; }
        public Nullable<decimal> Sec1_overall_percent { get; set; }
        public Nullable<decimal> Sec2_total_points_score { get; set; }
        public Nullable<decimal> Sec2_overall_percent { get; set; }
        public Nullable<int> PerformanceRating_Id { get; set; }
        public string PO_1 { get; set; }
        public string PO_2 { get; set; }
        public string PO_3 { get; set; }
        public string PO_4 { get; set; }
        public string PO_5 { get; set; }
        public string PO_6 { get; set; }
        public string PO_7 { get; set; }
        public string PO_8 { get; set; }
        public string PO_9 { get; set; }
        public string PO_10 { get; set; }
        public string kpi_1 { get; set; }
        public string kpi_2 { get; set; }
        public string kpi_3 { get; set; }
        public string kpi_4 { get; set; }
        public string kpi_5 { get; set; }
        public string kpi_6 { get; set; }
        public string kpi_7 { get; set; }
        public string kpi_8 { get; set; }
        public string kpi_9 { get; set; }
        public string kpi_10 { get; set; }
        public string date_to_complete_PO_1 { get; set; }
        public string date_to_complete_PO_2 { get; set; }
        public string date_to_complete_PO_3 { get; set; }
        public string date_to_complete_PO_4 { get; set; }
        public string date_to_complete_PO_5 { get; set; }
        public string date_to_complete_PO_6 { get; set; }
        public string date_to_complete_PO_7 { get; set; }
        public string date_to_complete_PO_8 { get; set; }
        public string date_to_complete_PO_9 { get; set; }
        public string date_to_complete_PO_10 { get; set; }
        public string PO_Rating_1 { get; set; }
        public string PO_Rating_2 { get; set; }
        public string PO_Rating_3 { get; set; }
        public string PO_Rating_4 { get; set; }
        public string PO_Rating_5 { get; set; }
        public string PO_Rating_6 { get; set; }
        public string PO_Rating_7 { get; set; }
        public string PO_Rating_8 { get; set; }
        public string PO_Rating_9 { get; set; }
        public string PO_Rating_10 { get; set; }
        public string ro_other_projects { get; set; }
        public string ro_strengths { get; set; }
        public string ro_improvements_followup { get; set; }
        public string ro_achievements { get; set; }
        public string DO_1 { get; set; }
        public string DO_2 { get; set; }
        public string DO_3 { get; set; }
        public string DO_4 { get; set; }
        public string DO_5 { get; set; }
        public string DO_6 { get; set; }
        public string DO_7 { get; set; }
        public string DO_8 { get; set; }
        public string DO_9 { get; set; }
        public string DO_10 { get; set; }
        public string actions_to_achieve_DO_1 { get; set; }
        public string actions_to_achieve_DO_2 { get; set; }
        public string actions_to_achieve_DO_3 { get; set; }
        public string actions_to_achieve_DO_4 { get; set; }
        public string actions_to_achieve_DO_5 { get; set; }
        public string actions_to_achieve_DO_6 { get; set; }
        public string actions_to_achieve_DO_7 { get; set; }
        public string actions_to_achieve_DO_8 { get; set; }
        public string actions_to_achieve_DO_9 { get; set; }
        public string actions_to_achieve_DO_10 { get; set; }
        public string current_or_future_role_1 { get; set; }
        public string current_or_future_role_2 { get; set; }
        public string current_or_future_role_3 { get; set; }
        public string current_or_future_role_4 { get; set; }
        public string current_or_future_role_5 { get; set; }
        public string current_or_future_role_6 { get; set; }
        public string current_or_future_role_7 { get; set; }
        public string current_or_future_role_8 { get; set; }
        public string current_or_future_role_9 { get; set; }
        public string current_or_future_role_10 { get; set; }
        public string date_to_complete_DO_1 { get; set; }
        public string date_to_complete_DO_2 { get; set; }
        public string date_to_complete_DO_3 { get; set; }
        public string date_to_complete_DO_4 { get; set; }
        public string date_to_complete_DO_5 { get; set; }
        public string date_to_complete_DO_6 { get; set; }
        public string date_to_complete_DO_7 { get; set; }
        public string date_to_complete_DO_8 { get; set; }
        public string date_to_complete_DO_9 { get; set; }
        public string date_to_complete_DO_10 { get; set; }
        public string outcomes_achieved_1 { get; set; }
        public string outcomes_achieved_2 { get; set; }
        public string outcomes_achieved_3 { get; set; }
        public string outcomes_achieved_4 { get; set; }
        public string outcomes_achieved_5 { get; set; }
        public string outcomes_achieved_6 { get; set; }
        public string outcomes_achieved_7 { get; set; }
        public string outcomes_achieved_8 { get; set; }
        public string outcomes_achieved_9 { get; set; }
        public string outcomes_achieved_10 { get; set; }
        public string staff_comments { get; set; }
        public Nullable<bool> ready_for_promotion { get; set; }
        public string to_promote_to { get; set; }
        public Nullable<bool> has_potential_for_promotion { get; set; }
        public string to_consider_on { get; set; }
        public Nullable<bool> needs_improvement { get; set; }
        public Nullable<bool> recommend_discipinary_action { get; set; }
        public Nullable<bool> salary_increment { get; set; }
        public Nullable<int> StatsCode_Id_salary_increment { get; set; }
        public Nullable<bool> performance_bonus { get; set; }
        public Nullable<int> StatsCode_Id_perf_bonus { get; set; }
        public string to_confirm_as { get; set; }
        public string ext_probation_months { get; set; }
        public string termination_last_day_of_service { get; set; }
        public Nullable<decimal> current_salary_fixed { get; set; }
        public Nullable<decimal> current_salary_vc { get; set; }
        public Nullable<decimal> salary_adj_fixed { get; set; }
        public Nullable<decimal> salary_adj_vc { get; set; }
        public Nullable<System.DateTime> salary_adj_eff_date { get; set; }
        public string month_of_next_annual_incr { get; set; }
        public Nullable<bool> ass_panel_approval { get; set; }
        public string ass_panel_comments { get; set; }
        public Nullable<bool> mgt_concurred_with_assessment { get; set; }
        public Nullable<bool> mgt_partially_concurred_with_assessment { get; set; }
        public Nullable<bool> mgt_donot_concur_with_assessment { get; set; }
        public string mgt_comments { get; set; }
        public Nullable<bool> disabled { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> appraisal_complete_date { get; set; }
        public Nullable<int> appraisal_update_count_after_completion { get; set; }
        public Nullable<bool> recommendation_others { get; set; }
        public string recommendation_others_specify { get; set; }
        public string job_scope_probationary_period { get; set; }
        public Nullable<bool> confirmation { get; set; }
        public Nullable<bool> extension { get; set; }
        public Nullable<bool> termination { get; set; }
    }
}
