//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PerformanceCriterion
    {
        public int PerformanceCriterion_Id { get; set; }
        public Nullable<int> Form_Id { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<int> SubSection_Id { get; set; }
        public string qn_title { get; set; }
        public string performance_criterion { get; set; }
        public Nullable<decimal> qno { get; set; }
        public Nullable<bool> disabled { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
    }
}
