//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WebAPI_RequestLog
    {
        public System.Guid ID { get; set; }
        public System.Guid RequestedSouceID { get; set; }
        public string RequestedPublicKey { get; set; }
        public string GeneratedKeyword { get; set; }
        public string EncryptedString { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
