//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Appraisal
    {
        public System.Guid Appraisal_Id { get; set; }
        public System.Guid SortOrder { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public Nullable<System.DateTime> assessment_startdate { get; set; }
        public Nullable<System.DateTime> assessment_enddate { get; set; }
        public Nullable<System.Guid> AppraisalType_Id { get; set; }
        public Nullable<System.Guid> AppraisalPurpose_Id { get; set; }
        public Nullable<System.Guid> AppraisalForm_Id { get; set; }
        public Nullable<bool> disabled { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
    }
}
