//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailNotification
    {
        public int EmailNotification_Id { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> timesent { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> sendstatus { get; set; }
        public Nullable<short> number_of_attempts { get; set; }
        public string errors { get; set; }
        public Nullable<int> notification_type_id { get; set; }
        public Nullable<int> AppraisalStaff_Id { get; set; }
    }
}
