//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMAS_Backend_WebEntities : DbContext
    {
        public PMAS_Backend_WebEntities()
            : base("name=PMAS_Backend_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CryptoKey> tbl_CryptoKey { get; set; }
        public virtual DbSet<tbl_WebAPIKey> tbl_WebAPIKey { get; set; }
    }
}
