//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WebAPIKey
    {
        public System.Guid ID { get; set; }
        public string RequestSource { get; set; }
        public string HandshakeKey { get; set; }
        public string HashKey { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
